name: flutter_instant_messenger
description: An instant messenger app for a school project to learn Flutter and Dart.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ^1.22.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^5.0.0-dev.3
  firebase_remote_config: ^0.4.0+2

  geolocator: ^6.1.1
  intl: ^0.16.1 
  provider: ^4.3.2+2
  image_picker: ^0.6.7+12
  modal_bottom_sheet: ^0.2.2
  uuid: ^2.2.2
  cached_network_image: ^2.3.3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SourceSansPro
      fonts:
      - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: SourceSansProItalic
      fonts:
      - asset: assets/fonts/SourceSansPro-Italic.ttf
